### ISSUE TITLE
Is this project dead? The install link 404s for twitter-thread-reader.js

### ISSUE THREAD

**Issue by gth001** [WhyWhatHow/powertoys4browser#3]
https://github.com/whywhathow/powertoys4browser/raw/main/js/twitter-thread-reader.js

**Comment by gth001** [comment]
nevermind, seems the markdown link is dead but found a copy at https://raw.githubusercontent.com/WhyWhatHow/powertoys4browser/master/js/twitter-thread-reader.js

**Comment by gth001** [comment]
and it works perfectly ^____^ thank you for this

the dead link is at [`After installing the userscript manager, click [here](https://github.com/whywhathow/powertoys4browser/raw/main/js/twitter-thread-reader.js) to install the userscript.
`](https://github.com/WhyWhatHow/powertoys4browser/blob/master/doc/twitter-thread-reader.md)

since I easily worked around it I suppose I should close this issue then

**Comment by WhyWhatHow** [comment]
Sorry for the late response. I've also replaced the outdated download link. Have fun and enjoy!
